[fr]
  languageName = "Français"
  contentDir = "content/fr"
  weight = 5
  [fr.params]
    languageISO = "FR"
    footer1 = '<small class="d-block mb-3 text-muted text-center">&copy; 2004–2022 Cellules Rapaces </br>par CoubyStark</small>'
    footer2 = 'Les défis Rapaces'
    footer3 = 'A propos'
    footer4 = 'Réseaux sociaux'
    footer5 = '⬆️'

[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    footer1 = '<small class="d-block mb-3 text-muted text-center">&copy; 2004–2022 Cellules Rapaces </br>by CoubyStark</small>'
    footer2 = 'Raptor Challenges'
    footer3 = 'About'
    footer4 = 'Social networks'
    footer5 = '⬆️'

[cn]
  languageName = "中国人"
  contentDir = "content/cn"
  weight = 15
  [cn.params]
    languageISO = "CN"
    footer1 = '<small class="d-block mb-3 text-muted text-center">&copy; 2004–2022 纤维素拉佩斯 </br>由 CoubyStark</small>'
    footer2 = '猛禽挑战'
    footer3 = '大约'
    footer4 = '社交网络'
    footer5 = '⬆️'

[es]
  languageName = "Español"
  contentDir = "content/es"
  weight = 20
  [es.params]
    languageISO = "ES"
    footer1 = '<small class="d-block mb-3 text-muted text-center">&copy; 2004–2022 Células rapaces </br>por CoubyStark</small>'
    footer2 = 'Desafíos de Raptor'
    footer3 = 'Acerca de'
    footer4 = 'Redes sociales'
    footer5 = '⬆️'

[de]
  languageName = "German"
  contentDir = "content/de"
  weight = 15
  [de.params]
    languageISO = "DE"

[nl]
  languageName = "Nederlands"
  contentDir = "content/nl"
  weight = 20
  [nl.params]
    languageISO = "NL"
