[[main]]
  name = "Presentazione"
  url = "/presentation/"
  weight = 10

[[main]]
  name = "Classifiche"
  weight = 25
  identifier = "resultats"
  url = "/resultats/"

[[main]]
  name = "Classificazione F-14B"
  weight = 30
  pre = "f-14-h"
  url = "/resultats/classements/classement_f14b"
  parent = "resultats"

[[main]]
  name = "Classificazione F-15C"
  weight = 40
  pre = "f-15-h"
  url = "/resultats/classements/classement_f15c"
  parent = "resultats"

[[main]]
  name = "Classificazione F-16C Block50"
  weight = 50
  pre = "f-16-h"
  url = "/resultats/classements/classement_f16c50"
  parent = "resultats"

[[main]]
  name = "Classificazione F/A-18C"
  weight = 60
  pre = "f-18-h"
  url = "/resultats/classements/classement_fa18c"
  parent = "resultats"

[[main]]
  name = "Classificazione JF-17"
  weight = 70
  pre = "jf-17-h"
  url = "/resultats/classements/classement_jf17"
  parent = "resultats"

[[main]]
  name = "Classificazione M-2000C"
  weight = 80
  pre = "M2000-h"
  url = "/resultats/classements/classement_m2000c"
  parent = "resultats"

[[main]]
  name = "Classificazione Mirage F1-CE"
  weight = 90
  pre = "mf1-h"
  url = "/resultats/classements/classement_mf1ce"
  parent = "resultats"

[[main]]
  name = "Classificazione MiG-21Bis"
  weight = 100
  pre = "mig21-h"
  url = "/resultats/classements/classement_mig21bis"
  parent = "resultats"

[[main]]
  name = "Classificazione MiG-29S"
  weight = 110
  pre = "mig29-h"
  url = "/resultats/classements/classement_mig29s"
  parent = "resultats"

[[main]]
  name = "Classificazione Su-27"
  weight = 120
  pre = "su27-h"
  url = "/resultats/classements/classement_su27"
  parent = "resultats"

[[main]]
  name = "Classificazione Su-33"
  weight = 130
  pre = "su33-h"
  url = "/resultats/classements/classement_su33"
  parent = "resultats"

[[main]]
  name = "Classificazione F-86F"
  weight = 140
  pre = "f-86-h"
  url = "/resultats/classements/classement_f86f"
  parent = "resultats"

[[main]]
  name = "Classificazione AJS-37"
  weight = 150
  pre = "ajs37-h"
  url = "/resultats/classements/classement_ajs37"
  parent = "resultats"

[[main]]
  name = "Classificazione F-5E"
  weight = 160
  pre = "f-5-h"
  url = "/resultats/classements/classement_f5e"
  parent = "resultats"

[[main]]
  name = "Classificazione MiG-15Bis"
  weight = 170
  pre = "mig15-h"
  url = "/resultats/classements/classement_mig15bis"
  parent = "resultats"

[[main]]
  name = "Classificazione MiG-19P"
  weight = 180
  pre = "mig19-h"
  url = "/resultats/classements/classement_mig19p"
  parent = "resultats"

[[main]]
  name = "Norme"
  weight = 200
  url = "/regles/"

[[main]]
  name = "Domande/Risposte"
  weight = 210
  url = "/questions/"

[[footer2]]
  name = "ELO Dogfight"
  url = "https://elodogfight.cellules-rapaces.fr/en/"
  weight = 10

[[footer2]]
  name = "Festa delle petroliere"
  url = "https://tankerparty.cellules-rapaces.fr"
  weight = 20

[[footer3]]
  name = "Cellules Rapaces"
  url = "https://www.cellules-rapaces.fr"
  weight = 10

[[footer3]]
  name = "Contatto"
  url = "/en/contact/"
  weight = 20

[[footer3]]
  name = "Note legali"
  url = "/en/mentionslegales/"
  weight = 30
